### ISSUE TITLE
Fatal error in Node.class.php: 'continue' not in the 'loop' or 'switch' context.

### ISSUE THREAD

**Issue by lincbergeson** [PhilGale92/docx#46]
I cloned the repository earlier today, pointed MAMP at the right directory, and tried to load http://localhost/docx. Chrome tells me "The localhost page isn't working."

MAMP's php_error.log says:
PHP Fatal error:  'continue' not in the 'loop' or 'switch' context in /Users/#####/docx/Docx/Node.class.php on line 553

Node.class.php has the following code on line 553:
`if (!isset($prevElement->nodeName)) continue;`

**Comment by PhilGale92** [comment]
I don't actually have any word files set up to test this anymore, so I don't know for sure how that will roll. Should be good though!
