### ISSUE TITLE
Can this project to  do the word file paging?

### ISSUE THREAD

**Issue by gsh895103731** [PhilGale92/docx#49]
hello phil, thanks for your job , everything is ok to used your packge,  but if my docx file has N pages, how can I do a page to read;

I try to solve this problem, but it is difficult for me, Can you help me check this question?

thanks again.

**Comment by PhilGale92** [comment]
Heya,
Glad to hear it still works. In terms of word files I think it would be possible to detect forced page breaks and give some tools in the parsed data so other people could do what they wish...

But standard page breaks would not be detectable without some pretty intensive calculations to find how much content is on the page and the set paper size etc.
Your best bet is probably to fake it by counting the number of elements in the parsed array and saying say the every X elements means a new page.

Hope thats useful!

**Comment by gsh895103731** [comment]
Okay, now we do not need to pagination, thank you very much！
