### ISSUE TITLE
Incorrect output for docx

### ISSUE THREAD

**Issue by kafayka** [PhilGale92/docx#51]
Hey Phil,

I've try to convert docx file 
[test111.docx](https://github.com/PhilGale92/docx/files/1187437/test111.docx) file attached

But it outputs with extra <ul> with <li's> in the start :( here's what I got:

string(6865) "<ul><li>Neuraxial Anesthesia Reduces the Need for Transfusions after THA</li><li>A study from Rush University Medical Center – reported at the MAOA annual meeting – also showed a reduction in the rate of complications with neuraxial versus general anesthesia.  </li><li><b>The largest study of its kind has shown that patients who receive </b><b>neuraxial</b><b> anesthesia for total hip </b><b>arthroplasty</b><b> </b><b>(THA) </b><b>are less l</b><b>ikely to need a blood transfusion after the procedure than patients who receive general anesthesia.</b></li><li><b>They were also less likely to experience complications such as deep infection and pneumonia.</b></li><li><b>For the study</b><b> – reported last week at the annual meeting of the Mid-America </b><b>Orthopaedic</b><b> Association</b><b> (MAOA)</b><b> – researchers </b><b>from Rush University Medical Center, Chicago, Illinois, evaluated data from the </b><b>National Surgical Quality Improvement </b><b>(NSQIP) </b><b>Database, which includes prospectively collected </b><b>data</b><b> on perioperative laboratory, co-morbidity, and postoperative complications. </b></li><li><b>The objective was to compare </b><b>neuraxial</b><b> versus general anesthesia with regard to </b><b>risk for blood transfusion </b><b>and </b><b>complications </b><b>i</b><b>n more than 29,000 patients who underwent primary THAs from 2005 to 2012</b><b>.</b></li></ul>“A growing body of literature has demonstrated an increased rate of complications with blood transfusions following primary total hip arthroplasty,” said Brett R. Levine, MD, senior author of the study. “While previous studies have demonstrated a decreased rate of complications with neuraxial anesthesia, these studies have included small numbers of patients undergoing heterogeneous orthopaedic procedures.”<b>Large Numbers – and </b><b>a </b><b>Surprise</b>That’s why the researchers turned to the NSQIP database. “The NSQIP database gives us access to a large volume of procedures and has been useful in identifying independent risk factors for several variables during a total joint arthroplasty,” Dr. Levine said.“In this case, we were able to review the data from almost 30,000 total hip replacements, including over 11,000 utilizing neuraxial anesthesia. The ability to evaluate such large quantities of procedures lends a greater validity to the final conclusions of our study.”<p>In total, data were retrieved for 29,452 procedures, 18,032 under general anesthesia and 11,420 under neuraxial anesthesia. The large number of general anesthesia cases was an unexpected finding, but did not affect the data analysis.</p><p>“We were surprised to discover that nearly 60% of providers in the NSQIP database utilized general anesthesia for primary total hip arthroplasty,” said Brian D. Haughom, MD, who presented the team’s data at the MAOA Annual Meeting. “Despite a trend toward increasing use of regional anesthesia, it is still not used in the majority of hip replacement cases.”</p><p>Dr. Levine speculated that this was the choice of the anesthesiologists on these cases, as surgeons typically prefer neuraxial anesthesia. “I do think spinal anesthesia is becoming more popular, and I bet the numbers will be reversed in the next 5 years,” he said. He also thinks the numbers would be different if they were evaluating anesthesia for total knee arthroplasty, in which regional anesthesia is more commonly used.&nbsp;</p><p><b>Favorable Results for</b><b> </b><b>Neuraxial</b><b> Anesthesia</b></p><p>The researchers used univariate analysis to evaluate postoperative complications between the two types of anesthesia. Multivariate analysis determined independent risk factors for blood transfusion following THA.</p><p>Surgical times were found to be shorter for patients who received neuraxial anesthesia (88.2 vs. 101.4 minutes; p&lt;0.001), as was the length of hospital stay (3.3 vs. 3.5 days; p=0.03). </p><p>The researchers also found that with neuraxial anesthesia, patients had lower rates of:</p><p>Overall complications (4.1% vs. 4.8%; p=0.006)</p><p>Medical complications (2.7 vs. 3.5%; p&lt;0.001)</p><p>Deep infection (0.23% vs. 0.37%; p=0.04)</p><p>Pneumonia (0.23% vs. 0.37%; p=0.04)</p><p>Unplanned intubation (0.16% vs. 0.29%; p=0.015)</p><p>Ventilation over 48 hours (0.04% vs. 0.13%; p=0.03)</p><p>Stroke (0.08% vs. 0.20%; p=0.013)Death (0.12% vs. 0.24%; p=0.025)</p><p>What about risk factors for postoperative blood transfusion? Overall, patients who received neuraxial anesthesia had a decreased risk of postoperative transfusion (OR=0.79; CI:0.69-0.91) than patients who received general anesthesia. </p><p>The researchers identified 3 independent risk factors for transfusion:</p><p>Female gender (OR=1.90; CI:1.66-2.18)</p><p>Operative time (OR=1.23 per 30 minutes; CI:1.18-1.29 )</p><p>History of hypertension (OR=1.33; CI:1.16-1.51)</p><p>“Our results demonstrate that neuraxial anesthesia decreased the rate of overall complications following primary total hip arthroplasty, and furthermore portended an 18% reduction in the rate of post operative blood transfusions,” said Dr. Haughom. </p><p>“While we suspected there may be advantages to neuraxial anesthesia, it was surprising to find such a large reduction in transfusion rates based upon anesthetic type as an independent risk factor.”</p><p><b>Recommendation for Practice</b></p><p>Dr. Levine believes these results suggest neuraxial anesthesia should have a larger role in THA.</p>“While the exact mechanism by which neuraxial anesthesia decreases the rate of complications and postoperative transfusions remains elusive, we feel that neuraxial anesthesia should be utilized whenever possible in the setting of a primary total hip arthroplasty,” he said. “By maximizing means to reduce complications and blood transfusions, it may be possible to reduce healthcare costs and readmissions in the future.“While this study highlights the impact of neuraxial anesthesia in regard to primary total hip arthroplasty, further studies are needed to elucidate the exact mechanisms leading to these findings.” <p><b>Source</b></p><ul><li><b>Poster 098: Does </b><b>Neuraxial</b><b> Anesthesia Decrease the Rate of Postoperative Complications and Blood Transfusions? An Analysis of 29,452 Primary Total Hip </b><b>Arthroplasty</b><b> Cases; presented by</b><b> </b><b>Brian D. </b><b>Haughom</b><b>, MD; William W. </b><b>Schairer</b><b>, MD; Michael D. Hellman, MD; Benedict U. </b><b>Nwachukwu</b><b>, MD; and Brett R. Levine, MD</b><b>, </b><b>at the Mid-Atlantic </b><b>Orthopaedic</b><b> Association Annual Meeting, </b><b>April 22-25, 2015, Hilton Head Island, South Carolina.</b>"

Could you please check what is wrong? Thanks.

**Comment by PhilGale92** [comment]
Thanks for this report, I'll hopefully have time to look into this in the
next couple of days .

**Comment by PhilGale92** [comment]
Heya, ive checked out the word file, and noticed inside the structure.xml the first paragraph is using <ilvl> tags, making it a list. Do you know if it was styled by hand to look like a standard paragraph by any chance?
Possibly related to #50

**Comment by kafayka** [comment]
Thanks for answer, 
Unfortunately I have only this doc and have no idea how it was edited :(

**Comment by PhilGale92** [comment]
Ok so i'm closing this issue out, im fairly sure when i last checked this issue it was due to the word file having a list, but using explicit styles to look like a normal paragraph.
As the word-recode im working on will hopefully be able to support extended word-run rendering it may be possible to be fixed then. (See #50  ) .
