### ISSUE TITLE
Images are not in their original position

### ISSUE THREAD

**Issue by gulfamproctur** [PhilGale92/docx#52]
This library works great since it preserves the spacing, images and text. 

But the problem is, images are not in their original position. Images are appearing in next line to every line of their actual position. For instance, I have four images in one single line. This line is enclosed in `<p>` tag without any images. All the four images then prints after the `</p>` tag.

Please fix this issue. I'm in middle of something very important.

**Comment by PhilGale92** [comment]
Huh i never did note on this, think i had deadlines at  the time.

Anyway so this annoyingly needs set of refactors that I'm not prepared to do in the main code base the way it pulls content into different text-runs is fairly archaic.

I'll leave the issue open so if I ever get around to a proper refactor/rewrite I'll have a reminder to be able to actually resolve it.

**Comment by PhilGale92** [comment]
Ok the recode version (still very much WIP) handles this. Better late than never ;)

**Comment by PhilGale92** [comment]
Ok from `recode branch`:
![image](https://user-images.githubusercontent.com/2852603/53298642-442b1700-3829-11e9-8f2b-39765c2d549f.png)

For comparison on `master`

![image](https://user-images.githubusercontent.com/2852603/53298647-e1398000-3828-11e9-8816-ea80c2efdbde.png)
